version: "3"
services:
  nodejs-server:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    container_name: node-api
    volumes:
      - ./backend:/app
      - /app/node_modules
  react-ui:
    depends_on: [nodejs-server]
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: react-ui
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
